### ISSUE TITLE
pack extract folder to exe again 

### ISSUE THREAD

**Issue by m0hamedessam** [extremecoders-re/pyinstxtractor#18]
is it possible to pack extract folder to exe again ?

**Comment by extremecoders-re** [comment]
The PyInstaller CArchive and ZlibArchive format is documented and open-source. I've a private tool for repacking Pyinstaller exe's which also allows adding, removing or editing existing files within it. So this is definitely possible.

There are also other ways to achieve the same result. Rather than repacking the exe, you can also build a new one out of the extracted files. The files inside the outpyz directory are the pure python dependencies of the application. Excluding the well known files, in standard Python, these usually reside inside the site-packages directory.

**Comment by m0hamedessam** [comment]
I did it with cx_freeze but will be nice if you share your tool.

**Comment by extremecoders-re** [comment]
Unfortunately wont be able to share the tool. Sorry about that.  But yes other approaches are possible including cx_freeze.

**Comment by m0hamedessam** [comment]
Thanks my friend for your concern anyway its done with cx_freeze without issues just need same python version with same bit (32 or 64)

**Comment by fuchsia74** [comment]
[https://github.com/in1nit1t/pyipx](url) this is good
