### ISSUE TITLE
folder empty

### ISSUE THREAD

**Issue by Facker007** [extremecoders-re/pyinstxtractor#64]
when i use pyinstxtractor
in PYZ-00.pyz_extracted is empty
![K L3)933{B`KWVI{IM LN@Y](https://user-images.githubusercontent.com/42063107/214030256-24a09f37-a5eb-41a1-a598-71100fd2b777.png)

**Comment by extremecoders-re** [comment]
Hard to tell without looking at the binary.

**Comment by Facker007** [comment]
this problem is my play ctf find
this is binary link：
https://drive.google.com/file/d/1sJTF8pKFQIn7lmUzArz6Sx4Z6kl5Lbxw/view?usp=sharing

**Comment by extremecoders-re** [comment]
> this problem is my play ctf find this is binary link： https://drive.google.com/file/d/1sJTF8pKFQIn7lmUzArz6Sx4Z6kl5Lbxw/view?usp=sharing

Sharing isn't enabled on that link.

**Comment by Facker007** [comment]
i'm sorry,so sorry.
this is my new link:
https://drive.google.com/file/d/1sJTF8pKFQIn7lmUzArz6Sx4Z6kl5Lbxw/view?usp=sharing

**Comment by extremecoders-re** [comment]
The exe was built with Python 3.10, so you need to use the same version of Python when running pyinstxtractor and it'll work fine.

![image](https://user-images.githubusercontent.com/12072382/214046218-36e1e97f-b15a-4495-aca0-37bbaae5167b.png)

Otherwise you can try pyinsxtractor-ng which doesn't need python to run.
https://github.com/pyinstxtractor/pyinstxtractor-ng/releases/tag/2022.12.03

**Comment by Facker007** [comment]
oh，thankyou
you are really good。bro
