### ISSUE TITLE
[!] Error : Missing cookie, unsupported pyinstaller version or not a pyinstaller archive

### ISSUE THREAD

**Issue by Shemdy** [extremecoders-re/pyinstxtractor#92]
Link to file -> https://gofile.io/d/9bGZ3I

**Comment by Shemdy** [comment]
![image](https://github.com/extremecoders-re/pyinstxtractor/assets/114173372/01e36374-5ba8-43b1-a8dc-ceaae921a16b)

**Comment by extremecoders-re** [comment]
Custom PyInstaller with magic `AAA\014\013\012\013\016`. 
Crypto key is `c132414b20084f12` and hidden in `pyimod01_archive.pyc`

Can use the above info in pyinstxtractor-ng to extract.

**Comment by Shemdy** [comment]
Интересно! Спасибо, но как им удалось изменить магическое число во время компиляции? Они изменили файлы pyinstaller?

**Comment by extremecoders-re** [comment]
> The only thing I wanted to clarify is how you identified the modified magic and discovered the new one.

For this specific file going through the hex dump was enough to figure the modified magic. The magic is located towards the end of the executable. You can load any standard pyinstaller exe and compare it with this one.

About the crypto key which is modified too regarding to where it is stored. In a standard exe, the crypto key is in a file with a name of the form XX_crypto_key.pyc. Here the key is inlined in the pyimod01_archive.pyc file and as a result automatic decryption in pyinstxtractor-ng doesn't work out of the box. The key can be recovered with a hex editor if you are familiar with pyc file structure and with decompiling/disassembling otherwise.

> And also what instructions the user brought when he modified PyInstaller.

Simple modifications to pyinstaller can always be done. Like to use a different magic you have to go through pyinstaller source code and replace all instances of it. For the crypto key part, the key can be hardcoded [here](https://github.com/pyinstaller/pyinstaller/blob/d1b6b520a017578a19e1cb9514752a4517755ee0/PyInstaller/loader/pyimod01_archive.py#L51) instead of loading it from another file. Small changes but gets the job done.

**Comment by Shemdy** [comment]
Thank you very much! You are a professional in your field
